// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkRJpaJH89Wg6ZpzX0fPVsr-McpsouJAI',
    appId: '1:1010671126192:web:eba10f820152e7fff95d75',
    messagingSenderId: '1010671126192',
    projectId: 'news-app-c3ec1',
    authDomain: 'news-app-c3ec1.firebaseapp.com',
    storageBucket: 'news-app-c3ec1.appspot.com',
    measurementId: 'G-WJHR146JBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkrlkxJtIXoqyuL-aXAXm_VuXP427Tps',
    appId: '1:1010671126192:android:0a4f956e1bd09677f95d75',
    messagingSenderId: '1010671126192',
    projectId: 'news-app-c3ec1',
    storageBucket: 'news-app-c3ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxi4LpB83u_FZDzB_3c6egB8w5AMPctrs',
    appId: '1:1010671126192:ios:f887a902331438fdf95d75',
    messagingSenderId: '1010671126192',
    projectId: 'news-app-c3ec1',
    storageBucket: 'news-app-c3ec1.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxi4LpB83u_FZDzB_3c6egB8w5AMPctrs',
    appId: '1:1010671126192:ios:f887a902331438fdf95d75',
    messagingSenderId: '1010671126192',
    projectId: 'news-app-c3ec1',
    storageBucket: 'news-app-c3ec1.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkRJpaJH89Wg6ZpzX0fPVsr-McpsouJAI',
    appId: '1:1010671126192:web:5021b40d961b27f1f95d75',
    messagingSenderId: '1010671126192',
    projectId: 'news-app-c3ec1',
    authDomain: 'news-app-c3ec1.firebaseapp.com',
    storageBucket: 'news-app-c3ec1.appspot.com',
    measurementId: 'G-TDT2M6036K',
  );
}
